version: "3"
services:
  db-master2:
    build:
      context: ./
      dockerfile: master2/Dockerfile
    restart: always
    environment:
      MYSQL_DATABASE: 'DB_Name'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3307:3306'
    # Where our data will be persisted
    volumes:
      - my-db-master2:/var/lib/mysql
    networks:
       net-mysql:
         ipv4_address: 172.20.0.3

# Names our volume
volumes:
  my-db-master2:

networks:
    net-mysql:
        ipam:
            driver: default
            config:
                - subnet: 172.20.0.0/16
